services:
  indexing:
    build: 
      context: .
      args:
        USE_CUDA: ${USE_CUDA}
        CUDA_VERSION: ${CUDA_VERSION}
    container_name: uncommon_rag-indexing
    env_file:
      - ../.env.global
      - .env
    ports:
      - "${INDEXING_PORT}:${INDEXING_INTERNAL_PORT}"
    environment:
      - PYTHONUNBUFFERED=1   
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - DEBIAN_FRONTEND=noninteractive
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    networks:
      - uncommon_rag-network
    restart: unless-stopped
# PostgreSQL과 Milvus 의존성은 애플리케이션 레벨에서 재시도 로직으로 처리
    # GPU 사용시에만 GPU 리소스 할당 (CPU 모드에서는 비활성화)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${INDEXING_INTERNAL_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  uncommon_rag-network:
    external: true
    name: ${NETWORK_NAME}