services:
  postgres:
    image: postgres:16-alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - ../.env.global
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_INIT_SCRIPT}:/docker-entrypoint-initdb.d/init.sql
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - uncommon_rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  uncommon_rag-network:
    external: true
    name: ${NETWORK_NAME}