services:
  milvus:
    image: milvusdb/milvus:v2.3.3
    container_name: uncommon_rag-milvus
    command: ["milvus", "run", "standalone"]
    env_file:
      - ../.env.global
      - .env
    environment:
      ETCD_USE_EMBED: true
      COMMON_STORAGETYPE: local
    volumes:
      - ./milvus_data:/var/lib/milvus
    ports:
      - "${MILVUS_PORT}:19530"
      - "${MILVUS_METRICS_PORT}:9091"
    networks:
      - uncommon_rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  uncommon_rag-network:
    external: true
    name: ${NETWORK_NAME}