services:
  rag-api:
    build:
      context: .
      args:
        USE_CUDA: ${USE_CUDA}
        CUDA_VERSION: ${CUDA_VERSION}
    container_name: uncommon_rag-api
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_INTERNAL_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_INTERNAL_PORT}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
    env_file:
      - ../.env.global
      - .env
    ports:
      - "${RAG_API_PORT}:${RAG_API_INTERNAL_PORT}"
    networks:
      - uncommon_rag-network
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${RAG_API_INTERNAL_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  uncommon_rag-network:
    external: true
    name: ${NETWORK_NAME}