services:
  router-ollama:
    image: ollama/ollama:latest
    container_name: uncommon_router-ollama
    hostname: uncommon_router-ollama
    restart: unless-stopped
    ports:
      - "${ROUTER_OLLAMA_PORT}:11434"
    volumes:
      - ./models:/root/.ollama
    networks:
      - ${NETWORK_NAME}
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  uncommon_rag-network:
    external: true